trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    set -x
    node -v
    npm -v
    npm install
  displayName: 'Install npm dependencies'

- script: |
    set -x
    npm run lint
  displayName: 'Lint code'

- script: |
    set -x
    npm run test
  displayName: 'Run tests'

- script: |
    set -x
    npm run build
  displayName: 'Build project'
