trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    set -x
    node -v
    npm -v
    cd admin
    npm install
    npm run build
  displayName: 'Build and package admin'

- script: |
    set -x
    cd backend
    npm install
    npm rebuild bcrypt
  displayName: 'Install npm dependencies and rebuild bcrypt for backend'

- script: |
    set -x
    cd frontend
    npm install
    npm run build
  displayName: 'Build and package frontend'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'admin/build'
    ArtifactName: 'admin'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'backend'
    ArtifactName: 'backend'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'frontend/build'
    ArtifactName: 'frontend'
    publishLocation: 'Container'
