trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    set -x
    node -v
    npm -v
    cd admin
    npm install
  displayName: 'Install npm dependencies for admin'

- script: |
    set -x
    cd admin
    npm run build
  displayName: 'Build project for admin'

- script: |
    set -x
    cd backend
    npm install
  displayName: 'Install npm dependencies for backend'

- script: |
    set -x
    cd backend
    npm run build
  displayName: 'Build project for backend'

- script: |
    set -x
    cd frontend
    npm install
  displayName: 'Install npm dependencies for frontend'

- script: |
    set -x
    cd frontend
    npm run build
  displayName: 'Build project for frontend'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'admin/build'
    ArtifactName: 'admin'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'backend/build'
    ArtifactName: 'backend'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'frontend/build'
    ArtifactName: 'frontend'
    publishLocation: 'Container'
